version: "3"
tasks:
  symlink:
    cmds:
      - rm ~/.config/local
      - ln -s ~/configs/lazyvim-config ~/.config/local
  test:
    deps:
      - symlink
    cmds:
      - NVIM_APPNAME=local nvim .
    silent: true
